spring.kafka.bootstrap-servers=localhost:9092
grpc.server.port=9090

spring.kafka.consumer.properties.schema.registry.url=http://localhost:8081
spring.kafka.consumer.properties.specific.avro.reader=true

collector.kafka.sensor-topic=telemetry.sensors.v1
collector.kafka.hub-topic=telemetry.hubs.v1

collector.kafka.bootstrap-servers=localhost:9092
collector.kafka.key-serializer=org.apache.kafka.common.serialization.StringSerializer
collector.kafka.value-serializer=ru.yandex.practicum.serialization.GeneralAvroSerializer