spring:
  application:
    name: analyzer
  datasource:
    url: jdbc:postgresql://localhost:5432/telemetry_analyzer
    username: dbuser
    password: 12345
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

analyzer:
  kafka:
    bootstrap-servers: localhost:9092
    topics:
      snapshots: telemetry.snapshots.v1
      hub-events: telemetry.hubs.v1
    consumer:
      snapshots-group: analyzer-snapshots
      hub-events-group: analyzer-hub-events

grpc:
  client:
    hub-router:
      address: 'static://localhost:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

logging:
  level:
    ru.yandex.practicum.analyzer: DEBUG